---
abstract: 'a GUI REPL written with Prima for the PDL community.'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prima-REPL
provides:
  App::Prima::REPL:
    file: lib/App/Prima/REPL.pm
    version: 0.02
  PrimaX::InputHistory:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  PrimaX::InputHistory::Output::Null:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  PrimaX::InputHistory::Output::StdOut:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  ih:
    file: lib/PrimaX/InputHistory.pm
    version: 0
requires:
  Prima: 1.33
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
