---
abstract: 'a GUI REPL written with Prima for the PDL community.'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.28
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prima-REPL
provides:
  App::Prima::REPL:
    file: lib/App/Prima/REPL.pm
    version: 0.03
  PrimaX::InputHistory:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  PrimaX::InputHistory::Output::Null:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  PrimaX::InputHistory::Output::StdOut:
    file: lib/PrimaX/InputHistory.pm
    version: 0
  ih:
    file: lib/PrimaX/InputHistory.pm
    version: 0
recommends:
  PDL: 0
  PDL::Graphics::Prima: 0
requires:
  Prima: 1.33
resources:
  bugtracker: http://github.com/run4flat/App-Prima-REPL/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/run4flat/App-Prima-REPL
version: 0.03
